---
- name: templating out Boundary controller configuration
  when: group_names is search('boundary_controllers')
  become: true
  block:
    - name: templating out boundary controller configuration file
      template:
        src: boundary-controller.hcl.j2
        dest: '{{ boundary_controller_file }}'
        owner: '{{ boundary_user }}'
        group: '{{ boundary_group }}'
        mode: '0640'
      notify:
        - restart boundary-controller daemon

    - name: templating out boundary controller systemd script
      template:
        src: boundary-controller.systemd.j2
        dest: /etc/systemd/system/boundary-controller.service
        owner: root
        group: root
        mode: '0644'
      register: controller_service_script
      notify:
        - restart boundary-controller daemon

- name: templating out Boundary worker configuration
  when: group_names is search('boundary_workers')
  become: true
  block:
    - name: templating out boundary worker configuration file
      template:
        src: boundary-worker.hcl.j2
        dest: '{{ boundary_worker_file }}'
        owner: '{{ boundary_user }}'
        group: '{{ boundary_group }}'
        mode: '0640'
      notify:
        - restart boundary-worker daemon

    - name: templating out boundary worker systemd script
      template:
        src: boundary-worker.systemd.j2
        dest: /etc/systemd/system/boundary-worker.service
        owner: root
        group: root
        mode: '0644'
      register: worker_service_script
      notify:
        - restart boundary-worker daemon

# Must do this before we scan for service status
- name: reload systemd config if necessary
  systemd:
    daemon_reload: yes
  become: true
  when: worker_service_script is changed or controller_service_script is changed
