---
- name: templating out Boundary controller configuration
  when: "'boundary_controllers' in group_names"
  block:
    - name: templating out boundary controller configuration file
      template:
        src: boundary-controller.hcl.j2
        dest: '{{ boundary_controller_file }}'
        owner: '{{ boundary_user }}'
        group: '{{ boundary_group }}'
        mode: '0640'
      notify:
        - restart boundary-controller daemon

    - name: templating out boundary controller systemd script
      template:
        src: boundary-controller.systemd.j2
        dest: /etc/systemd/system/boundary-controller.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - reload boundary-controller daemon

    - name: initializing database for boundary
      shell: "{{ boundary_command }} database init -config {{ boundary_controller_file }} {{ boundary_db_init_flags }}"
      run_once: True
      register: boundary_database_init
      changed_when:
        - "'Database has already been initialized.' not in boundary_database_init.stderr"
      failed_when:
        - "boundary_database_init.rc != 0"
        - "'Database has already been initialized.' not in boundary_database_init.stderr"
      when: not lookup('env', 'MOLECULE_FILE')  # skip when testing for now

    - name: starting and enabling boundary-controller
      systemd:
        name: boundary-controller
        enabled: yes
        state: started
      when: not lookup('env', 'MOLECULE_FILE')  # skip when testing for now

- name: templating out Boundary worker configuration
  when: "'boundary_workers' in group_names"
  block:
    - name: templating out boundary worker configuration file
      template:
        src: boundary-worker.hcl.j2
        dest: '{{ boundary_worker_file }}'
        owner: '{{ boundary_user }}'
        group: '{{ boundary_group }}'
        mode: '0640'
      notify:
        - restart boundary-worker daemon

    - name: templating out boundary worker systemd script
      template:
        src: boundary-worker.systemd.j2
        dest: /etc/systemd/system/boundary-worker.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - reload boundary-worker daemon

    - name: starting and enabling boundary-worker
      systemd:
        name: boundary-worker
        enabled: yes
        state: started
      when: not lookup('env', 'MOLECULE_FILE')  # skip when testing for now
